// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohlsguszmyrwysdqhejj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9obHNndXN6bXlyd3lzZHFoZWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjcyNzMsImV4cCI6MjA3MTkwMzI3M30.WTBB80uY6shEziCtd2-xe4UGSvrlLGmbcSw-p85jJqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});